server:
  port: 30001
spring:
  application:
    name: provider-customer-profile
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.102.124:23306/customer_profile?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: H03089611.
  redis:
    host: 8.129.126.4
    port: 26379
    database: 1
    password: gcs123
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.102.124:28848

#mybatis-plus 配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: '*'