server:
  port: 30002
spring:
  application:
    name: consumer-customer-profile
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.102.124:28848

provider:
  url: http://provider-customer-profile
